---
title: "Napoli - Milan: A Network Analysis"
author: "Davide Mascolo"
date: "2023-07-03"
output: html_document
---

## Import Libraries
```{r}
## Load Utils
library(readxl)
library(igraph)
library(ggplot2)
library(scales)
library(gridExtra)
library(grid)
library(kableExtra)
```



## Custom Functions and Global Variables
```{r}
## Set colors
color_att = "red"
color_def = "green"
color_cen = "orange"
color_por = "yellow"

## Players
att <- c("18", "11", "21", "77", "81")
cen <- c("7", "20", "68", "99", "91")
def <- c("3", "6", "13", "22", "5")
por <- c("1")

## Passing Networks
## Create a function that computes the number of passes for each player
num_passes <- function(data){
  ## Input: Data
  ## Output: Best 5 players
  
  ## Players who have made the most passes
  list_1 <- sort(table(data$Player_1), decreasing = T)
  
  ## Players who have received the most playable balls from their teammates
  list_2 <- sort(table(data$Player_2), decreasing = T)
  
  return(list("Passes Completed" = list_1, "Passes Received" = list_2))
}

## Create a function to process data and create a graph
create_graph_data <- function(data){
  ## Create the graph and compute the degree of each node
  data$weight <- 1
  g   <- graph_from_data_frame(data, directed = T)
  deg <- degree(g)
  
  ## Aggregate the edges between the same nodes
  agg_data <- aggregate(weight ~ data$Player_1 + data$Player_2,
                        data = data, FUN = sum)
  graph <- graph_from_data_frame(agg_data, directed = T)
  
  ## Nodes' degree
  degrees = c()
  for (node in V(graph)$name){
    degrees = c(degrees, deg[as.character(node)])
  }
  
  return(list("agg_data" = agg_data, "graph" = graph, "degrees" = degrees))
}

## Function to color the graph according to the Player_ position
graph_colors <- function(agg_data) {
  agg_data$color <- 1
  for (i in 1:dim(agg_data)[1]) {
    if (agg_data[i,1] %in% att) {
      agg_data$color[i] = color_att
    }else if(agg_data[i,1] %in% def){
      agg_data$color[i] = color_def
    }else if(agg_data[i,1] %in% cen){
      agg_data$color[i] = color_cen
    }else{
      agg_data$color[i] = color_por
    }
  }
  return(agg_data)
}

## Create lists of players
players_first_half  <- c("Kim", "Mario Rui", "Rrhamani", "Di Lorenzo",
                         "Lobotka", "Anguissa", "Meret", "Zielinski",
                         "Politano", "Kvaratskhelia", "Simeone")
players_second_half <- c("Kim", "Juan Jesus", "Elmas", "Rrhamani",
                         "Simeone", "Anguissa", "Meret", "Mario Rui",
                         "Politano", "Lobotka", "Kvaratskhelia", "Zielinski",
                         "Raspadori", "Di Lorenzo", "Ndombele", "Lozano")
players_whole       <- c("Kim", "Juan Jesus", "Mario Rui", "Elmas",
                         "Rrhamani", "Simeone", "Di Lorenzo",
                         "Lobotka", "Anguissa", "Meret", "Zielinski",
                         "Politano", "Kvaratskhelia", "Raspadori",
                         "Ndombele", "Lozano")

## Create lists of colors
colors_first_half  <- c(color_def, color_def, color_def, color_def,
                        color_cen, color_cen, color_por, color_cen,
                        color_att, color_att, color_att)
colors_second_half <- c(color_def, color_def, color_cen, color_def,
                        color_att, color_cen, color_por, color_def,
                        color_att, color_cen, color_att, color_cen,
                        color_att, color_def, color_cen, color_att)
colors_whole       <- c(color_def, color_def, color_def, color_cen, 
                        color_def, color_att, color_def, color_cen,
                        color_cen, color_por, color_cen, color_att,
                        color_att, color_att, color_cen, color_att)

## Create a function that look at the nodes and assign labels
assign_labels <- function(graph_to_label, players, colors){
  ## Input: Graph, List of Players, List of Colors
  ## Output: Final graph with labels

  ## Set labels
  V(graph_to_label$graph)$labels <- players
  ## Set colors
  V(graph_to_label$graph)$colors <- colors
  graph_to_label$agg_data <- graph_colors(graph_to_label$agg_data)
  
  return(graph_to_label)
}

## Create a function for Dynamic Plot
dynamic_plot <- function(graph_to_plot){
  ## Input: Graph
  ## Output: Dynamic Plot
  tkplot(graph_to_plot$graph,
       vertex.size = graph_to_plot$degrees*250/
         sum(graph_to_plot$degrees), ## normalized
       edge.width = graph_to_plot$agg_data$weight*250/
         sum(graph_to_plot$agg_data$weight),
       vertex.label = V(graph_to_plot$graph)$labels,
       vertex.color = V(graph_to_plot$graph)$colors,
       vertex.label.font = 2, 
       edge.label.font = 1, 
       edge.label.cex = 1, 
       vertex.label.cex = 1,
       edge.arrow.size = 0.5,
       edge.curved = 0.3,
       edge.color = graph_to_plot$agg_data$color)
}

## Players' Metrics
summary_players_metrics <- function(graph_to_use){
  ## Input: Graph to use
  ## Output: A matrix with metrics for each player
  player_matrix <-  matrix(NA, nrow = length(V(graph_to_use)),
                           ncol = 4)
  for(i in 1:length(V(graph_to_use))){
    player_matrix[i, 1] <- round(transitivity(graph_to_use,
                                             type = "local"), 3)[i]
    player_matrix[i, 2] <- round(betweenness(graph_to_use,
                                            v = V(graph_to_use)[i],
                                            directed = TRUE,
                                            normalized = T), 3)
    player_matrix[i, 3] <- round(closeness(graph_to_use,
                                          vids = V(graph_to_use)[i],
                                          mode = "in",
                                          normalized = T), 3)
    player_matrix[i, 4] <- round(closeness(graph_to_use,
                                          vids = V(graph_to_use)[i],
                                          mode = "out",
                                          normalized = T), 3)
  }
  rownames(player_matrix) <- V(graph_to_use)$labels
  colnames(player_matrix) <- c("Clustering coefficient",
                               "Betweenness centrality",
                               "Closeness centrality - in",
                               "Closeness centrality - out")
  return(player_matrix)
}

## Zone Player Graph
## Function to create a graph where the nodes are the zone-player tuples
zone_player_graph <- function(df){
  ## Input: Data
  ## Output: Graph Zone
  
  ## Paste together player and zone
  zp_data <- data.frame(paste(df$Player_1, df$Zone_1), 
                        paste(df$Player_2, df$Zone_2), df$Minute)
  colnames(zp_data) <- c("Player_1", "Player_2", "Minute")
  ## Use the previous function
  g_zp <- create_graph_data(zp_data)
  return(g_zp)
}

## Degree distribution
## Function to plot the degree distribution
degree_distr_plot <- function(g, g_mode) {
  ## Compute the degrees
  G.degrees <- degree(g, mode = g_mode)
  G.degree.histogram <- as.data.frame(table(G.degrees))
  G.degree.histogram$G.degrees <-
    as.numeric(levels(G.degree.histogram$G.degrees))
  
  if(g_mode == "in"){
    lab <- "In-Degree"
  }else{
    lab <- "Out-Degree"
  }
  
  ## Histogram
  hist = ggplot(as.data.frame(G.degrees), aes(x = G.degrees)) + 
    geom_histogram(color = "darkblue", fill = "lightblue",
                   position = position_dodge(0.7),
                   size = 0.8, alpha = 0.8, binwidth = 1) +
    scale_x_continuous(breaks = pretty_breaks()) + 
    scale_y_continuous(breaks = pretty_breaks(), limits = c(0,30)) +
    xlab(lab) +
    ylab("Frequency") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15), 
          legend.title = element_blank(), 
          legend.position = "bottom",
          legend.text = element_text(size = 9, face = "bold"),
          axis.text = element_text(size = 15, face = "bold"),
          axis.title = element_text(size = 15, face = "bold"),
          aspect.ratio = 1,
          axis.title.y = element_text(margin = margin(t = 0, r = 5,
                                                      b = 0, l = 0)))
  
  ## Points
  p <- ggplot(G.degree.histogram, aes(x = G.degrees, y = Freq)) +
    geom_point(size = 3, color = "darkblue", alpha = 0.5) +
    scale_y_continuous(breaks = pretty_breaks(), limits = c(0,30)) +
    xlab(lab) +
    ylab("Frequency") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15), 
          legend.title = element_blank(), 
          legend.position = "bottom",
          legend.text = element_text(size = 9, face = "bold"),
          axis.text = element_text(size = 15, face = "bold"),
          axis.title = element_text(size = 15, face = "bold"),
          aspect.ratio = 1, axis.title.y = element_text(margin =
                                    margin(t = 0, r = 5, b = 0, l = 0)))

  return(list("hist" = hist, "p" = p))
}

## 15 minutes window analysis
metric_every_15_min <- function(df, min = 15){
  ## Input: Data
  ## Output: Clustering Plot for each minute
  minutes <- unique(df$Minute)
  mat_clu <- matrix(NA, ncol = 5, nrow = length(minutes))
  
  for (i in 1:length(minutes)) {
    window <- minutes[i]-min
    sta    <- 0
    if (window < 0){
      cut_first_half <- df[which(df$Minute >= 0 & df$Minute <= minutes[i]),]
      sta = 0
    }else{
      cut_first_half <- df[which(df$Minute >= window & df$Minute <=
                                  minutes[i]),]
      sta <- window
    }
    cut_first_half$weight <- 1
    edge_list <- aggregate(weight ~ cut_first_half$Player_1 +
                             cut_first_half$Player_2,
                           data = cut_first_half, 
                           FUN = sum)
    g_clu <- graph_from_data_frame(edge_list, directed = TRUE)
    mat_clu[i,1] <- transitivity(g_clu, type = "average")
    mat_clu[i,2] <- sta
    mat_clu[i,3] <- minutes[i]
    mat_clu[i,4] <- mean(degree(g_clu))
    mat_clu[i,5] <- sd(degree(g_clu))
  }
  
  ## Plot
  p_clu_coeff <- ggplot(as.data.frame(mat_clu), aes(mat_clu[,3],
                                                    mat_clu[,1])) + 
    geom_line(color = "blue", lwd = 1.5) + 
    geom_point(color = "orange", lwd = 2) +
    scale_x_continuous(breaks = pretty_breaks()) + 
    scale_y_continuous(breaks = pretty_breaks()) +
    theme_classic() +
    xlab("Minute") + 
    ylab("Clustering coefficient") +
    theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15), 
          legend.title = element_blank(), 
          legend.position = "bottom",
          legend.text = element_text(size = 9, face = "bold"),
          axis.text = element_text(size = 15, face = "bold"),
          axis.title = element_text(size = 15, face = "bold"),
          aspect.ratio = 1,
          axis.title.y = element_text(margin =
                                        margin(t = 0, r = 5, b = 0, l = 0)))
  ## Plot
  p_mean_degree <- ggplot(as.data.frame(mat_clu), aes(mat_clu[,3],
                                                      mat_clu[,4])) + 
    geom_line(aes(colour = "Mean"), lwd = 1.5) + 
    geom_line(aes(y = mat_clu[,4]+mat_clu[,5],
                  colour = "Mean +/- Std"), lwd = 0.8) +
    geom_line(aes(y = mat_clu[,4]-mat_clu[,5],
                  colour = "Mean +/- Std"), lwd = 0.8) +
    geom_ribbon(aes(x = mat_clu[,3],
                    ymin = mat_clu[,4]-mat_clu[,5],
                    ymax = mat_clu[,4]+mat_clu[,5]),
                fill = "green", alpha = 0.1)+
    geom_point(color = "orange", lwd = 2) +
    scale_x_continuous(breaks = pretty_breaks()) + 
    scale_y_continuous(breaks = pretty_breaks()) +
    scale_color_manual(values = c("Mean"="blue",
                                  "Mean +/- Std" = "darkgreen"), 
                      name = "Legend") +
    theme_classic() +
    xlab("Minute") + 
    ylab("Mean degree") +
    theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15), 
          legend.title = element_blank(), 
          legend.position = "right",
          legend.text = element_text(size = 9, face = "bold"),
          axis.text = element_text(size = 15, face = "bold"),
          axis.title = element_text(size = 15, face = "bold"),
          aspect.ratio = 1,
          axis.title.y = element_text(margin =
                                        margin(t = 0, r = 5, b = 0, l = 0)))
  
  return(list("p_clu_coeff" = p_clu_coeff,
              "p_mean_degree" = p_mean_degree))
}

## Zone of the player with the highest degree (every 15 min) (paper Spagna)
highest_degree_zone_15_min <- function(df, min = 15){
  df <- data.frame(paste(df$Player_1, df$Zone_1), 
                  paste(df$Player_2, df$Zone_2), df$Minute)
  colnames(df) <- c("Player_1", "Player_2", "Minute")
  minutes <- unique(df$Minute)
  mat_clu <- matrix(NA, ncol = 2, nrow = length(minutes))
  
  for (i in 1:length(minutes)) {
    window <- minutes[i]-min
    sta <- 0
    if (window < 0){
      cut_first_half <- df[which(df$Minute >= 0 &
                                   df$Minute <= minutes[i]),]
      sta <- 0
    }else{
      cut_first_half = df[which(df$Minute >= window &
                                  df$Minute <= minutes[i]),]
      sta = window
    }
    cut_first_half$weight <- 1
    edge_list <- aggregate(weight ~ cut_first_half$Player_1 +
                             cut_first_half$Player_2,
                           data = cut_first_half, 
                           FUN = sum)
    g_clu <- graph_from_data_frame(edge_list, directed = T)
    d <- degree(g_clu)[which(degree(g_clu) == max(degree(g_clu)))][1]
    d <- substr(names(d), start = nchar(names(d)), stop = nchar(names(d)))
    mat_clu[i,1] <- as.numeric(d)
    mat_clu[i,2] <- minutes[i]
  }
  
  p_15_degree <- ggplot(as.data.frame(mat_clu),
                        aes(mat_clu[,2],
                            mat_clu[,1])) + 
    geom_point(color = "orange", size = 3) +
    geom_segment( aes(x = as.vector(mat_clu[,2]),
                      xend = as.vector(mat_clu[,2]), y = 0,
                      yend = as.vector(mat_clu[,1]))) +
    scale_x_continuous(breaks = pretty_breaks()) + 
    scale_y_continuous(breaks = pretty_breaks(n = 9)) +
    annotate("text", x = 0, y = 9, label = "") +
    theme_classic() +
    xlab("Minute") + 
    ylab("Zone") +
    theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15), 
          legend.title = element_blank(), 
          legend.position = "bottom",
          legend.text = element_text(size = 9, face = "bold"),
          axis.text = element_text(size = 15, face = "bold"),
          axis.title = element_text(size = 15, face = "bold"),
          aspect.ratio = 1,
          axis.title.y = element_text(margin =
                                        margin(t = 0, r = 5, b = 0, l = 0)))
  return(p_15_degree)
}

zone_graph <- function(data){
  ## Input: Data
  ## Output: Graph with attributes
  
  ## Create the graph and compute the degree of each zone
  z     <- graph_from_data_frame(data, directed = T)
  deg_z <- degree(z)
  
  ## Aggregate the edges between the same nodes
  data$weight = 1
  agg_data = aggregate(weight ~ data$Zone_1 + data$Zone_2,
                       data = data, FUN = sum)
  graph = graph_from_data_frame(agg_data, directed = T)
  
  ## Nodes' degree
  degrees = c()
  for (node in V(graph)$name) {
    degrees = c(degrees, deg_z[as.character(node)])
  }
  return(list("graph" = graph, "agg_data" = agg_data, "degrees" = degrees))
}

## Community Detection
community_detection <- function(gra){
  clp_edge_betw <- cluster_edge_betweenness(gra, weights = NA)
  LOC <- layout_components(gra)
  plot(clp_edge_betw, gra,layout = LOC, 
       vertex.label = "",
       vertex.size = 8,
       edge.arrow.size = 0.01, main = "Edge-betweenness")
  
  clp_label_prop <- cluster_label_prop(gra)
  plot(clp_label_prop, gra,
       vertex.label = "",
       vertex.size  = 8,
       edge.arrow.size = 0.01, main = "Label-propagating")
  
  ## Louvain works only with undirected graphs
  clp_walktrap_prop <- cluster_walktrap(gra)
  plot(clp_walktrap_prop, gra,
       vertex.label = "",
       vertex.size = 8,
       edge.arrow.size = 0.01, main = "Walktrap")
  
  clp_infomap_prop <- cluster_infomap(gra)
  plot(clp_infomap_prop, gra,
       vertex.label = "",
       vertex.size = 8,
       edge.arrow.size = 0.01, main = "Infomap")
  
  return(list("clp_edge_betw" = clp_edge_betw,
              "clp_label_prop" = clp_label_prop,
              "clp_walktrap_prop" = clp_walktrap_prop,
              "clp_infomap_prop" = clp_infomap_prop))
}
```


## Set directory and Load Data
```{r setup, include = FALSE}
## Set directory
dir_data <- "C:/Users/david/Documents/Università/Magistrale/Secondo Anno/Secondo Semestre/DDMCS/Project/Data/Nap-Milan"
## First and Second Half
first_half  <- "Nap_Milan_First_Half.xlsx"
second_half <- "Nap_Milan_Second_Half.xlsx"

## Load Data First Half
df_1 <- read_excel(paste(dir_data, first_half, sep = "/"))
## Load Data Second Half
df_2 <- read_excel(paste(dir_data, second_half, sep = "/"))
```


## Data Wrangling
```{r}
## Reorder columns, format: Player_ 1, Player_, 2, Minute, Zone 1, Zone 2
df_1 <- df_1[c(2, 4, 1, 3, 5)]
df_2 <- df_2[c(2, 4, 1, 3, 5)]

## Combine unique dataset
df_all <- rbind(df_1, df_2)

## Check
dim(df_1)
dim(df_2)
dim(df_all)
```


## EDA
```{r}
## Number of passes
message("Number of passes first half: ", dim(df_1)[1])
message("Number of passes second half: ", dim(df_2)[1])
message("Number of passes total: ", dim(df_all)[1])
```

```{r}
## Number of passes for each player

## First Half
message("First Half")
num_passes(df_1)
message("\n")

## Second Half
message("Second Half")
num_passes(df_2)
message("\n")

## Match
message("Whole Match")
num_passes(df_all)
message("\n")
```


## Network analysis
### Passing Networks
```{r}
## Create Graph for First Half
g_first_half <- create_graph_data(df_1)
## Creat Graph for Second Half
g_second_half <- create_graph_data(df_2)
## Create Graph for the whole match
g_all <- create_graph_data(df_all)
```

```{r}
## Apply

## First Half
g_first_half  <- assign_labels(g_first_half, players_first_half,
                               colors_first_half)

## Second Half
g_second_half <- assign_labels(g_second_half, players_second_half,
                               colors_second_half)

## Whole Match
g_all         <- assign_labels(g_all, players_whole, colors_whole)
```

```{r}
## First Half
dynamic_plot(g_first_half)
```

```{r}
## First Half
dynamic_plot(g_second_half)
```

```{r}
## First Half
dynamic_plot(g_all)
```

### Players' metrics
```{r}
## Metrics on original graph with non-aggregated edges
original_graph           <- graph_from_data_frame(df_all)
V(original_graph)$labels <- players_whole

summary_metrics     <- summary_players_metrics(original_graph)
kable(as.data.frame(summary_metrics)) %>% 
  kable_styling() %>% 
  row_spec(c(7, 8), bold = T, color = "blue",
           background = "steelblue") %>% 
  save_kable(file = "Player_Metrics_Napoli_Juve.png")
```

### Zone-player Analysis
```{r}
## Create Graph

## First Half
g_first_half_zp  <- zone_player_graph(df_1)
## Second Half
g_second_half_zp <- zone_player_graph(df_2)
## Whole Match
g_whole_zp       <- zone_player_graph(df_all)
```

### Degree Distribution
```{r}
## Apply
h1 <- degree_distr_plot(g_whole_zp$graph, "in")$hist
p1 <- degree_distr_plot(g_whole_zp$graph, "in")$p
h2 <- degree_distr_plot(g_whole_zp$graph, "out")$hist
p2 <- degree_distr_plot(g_whole_zp$graph, "out")$p

## Plot
grid.arrange(h1, p1, h2, p2)
```

### Strength distribution
```{r}
## Plot
strength_plot <- ggplot(as.data.frame(table(g_whole_zp$agg_data$weight)),
            aes(x = Var1, y = Freq)) +
  geom_point(size = 3, color = "darkblue", alpha = 0.5) +
  xlab("Weight") +
  ylab("Frequency") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15), 
        legend.title = element_blank(), 
        legend.position = "bottom",
        legend.text = element_text(size = 9, face = "bold"),
        axis.text = element_text(size = 15, face = "bold"),
        axis.title = element_text(size = 15, face = "bold"),
        aspect.ratio = 1,
        axis.title.y = element_text(margin =
                                      margin(t = 0, r = 5, b = 0, l = 0)))
strength_plot
```

### 15 minutes time-window analysis
```{r}
## Whole Match
plot_5_window  <- metric_every_15_min(df_all, min = 5)
plot_10_window <- metric_every_15_min(df_all, min = 10)
plot_15_window <- metric_every_15_min(df_all, min = 15)
```
```{r}
# Min = 5
## Plot Clustering Coefficient (min = 5, 10, 15)
p1 <- plot_5_window$p_clu_coeff +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 5")

## Plot Mean Degree
p2 <- plot_5_window$p_mean_degree +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 5")

# Min = 10
## Plot Clustering Coefficient
p3 <- plot_10_window$p_clu_coeff +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 10")

## Plot Mean Degree
p4 <- plot_10_window$p_mean_degree +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 10")

# Min = 15
##Plot Clustering Coefficient
p5 <- plot_15_window$p_clu_coeff +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 15")

## Plot Mean Degree
p6 <- plot_15_window$p_mean_degree +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 15")
```

```{r}
## Check
## Min = 5
grid.arrange(p1, p2, ncol = 2, top = textGrob("Window = 5"))
## Min = 10
grid.arrange(p3, p4, ncol = 2, top = textGrob("Window = 10"))
## Min = 15
grid.arrange(p5, p6, ncol = 2, top = textGrob("Window = 15"))
```

### Zone of the player with the highest degree (every 15 min)
```{r}
## Whole Match
plot_5_degree  <- highest_degree_zone_15_min(df_all, min = 5)
plot_10_degree <- highest_degree_zone_15_min(df_all, min = 10)
plot_15_degree <- highest_degree_zone_15_min(df_all, min = 15)
```

```{r}
## Plot Degree for each 5 minutes
p5_degree <- plot_5_degree +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 5 minutes")

## Plot Degree for each 10 minutes
p10_degree <- plot_10_degree +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 10 minutes")

## Plot Degree for each 15 minutes
p15_degree <- plot_15_degree +
  geom_vline(xintercept = 17, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 25, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 59, color = "red", lwd = 0.9) +
  geom_vline(xintercept = 67, color = "red", lwd = 0.9) +
  annotate("text", x = 15.5, y = 0.15, label = "0-1", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 23.5, y = 0.15, label = "0-2", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = .1) +
  annotate("text", x = 57.5, y = 0.15, label = "0-3", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = -0.3) +
  annotate("text", x = 65.5, y = 0.15, label = "0-4", angle = "90",
           fontface = "bold", size = 5, color = "red", vjust = 0.3) +
  ggtitle("Window = 15 minutes")

## Plot
grid.arrange(p5_degree, p10_degree, p15_degree, ncol = 3)
## Best: 5 minutes window
```

### Graph with the zones as nodes
```{r}
## Data manipulation
first_half_z     <- df_1[,c(4,5,1,2,3)]
second_half_z    <- df_2[,c(4,5,1,2,3)]
match_z          <- df_all[,c(4,5,1,2,3)]

## Plots

## First Half match
first_half_zone  <- zone_graph(first_half_z)
## First Half match
second_half_zone <- zone_graph(second_half_z)
## First Half match
match_zone       <- zone_graph(match_z)

## Check the nodes and assign the labels
## First Half
V(first_half_zone$graph)
V(first_half_zone$graph)$labels <- c("1", "2", "3", "4", "5",
                                     "6", "7", "8", "9")
V(first_half_zone$graph)$colors <- c("yellow", "green", "green", "green",
                                     "orange", "red", "red", "red",
                                     "red")
## Second Half
V(first_half_zone$graph)
V(second_half_zone$graph)$labels <- c("1", "2", "3", "4", "5",
                                     "6", "7", "8", "9")
V(second_half_zone$graph)$colors <- c("yellow", "green", "green", "green",
                                     "orange", "red", "red", "red",
                                     "red")
## Match
V(match_zone$graph)
V(match_zone$graph)$labels <- c("1", "2", "3", "4", "5",
                                     "6", "7", "8", "9")
V(match_zone$graph)$colors <- c("yellow", "green", "green", "green",
                                     "orange", "red", "red", "red",
                                     "red")
```

```{r}
## Plot First Half
tkplot(first_half_zone$graph,
       vertex.size = first_half_zone$degrees*250/
         sum(first_half_zone$degrees),
       vertex.color = V(first_half_zone$graph)$colors,
       edge.width = first_half_zone$agg_data$weight*250/
         sum(first_half_zone$agg_data$weight),
       vertex.label = V(first_half_zone$graph)$labels,
       vertex.label.font = 2,
       vertex.label.color = "black",
       vertex.label.cex = 2,
       edge.label.font = 1, 
       edge.label.cex = 1,
       vertex.label.size = 5,
       edge.arrow.size = 0.5,
       edge.curved = 0.3)
```

```{r}
## Plot Second Half
tkplot(second_half_zone$graph,
       vertex.size = second_half_zone$degrees*250/
         sum(second_half_zone$degrees),
       vertex.color = V(second_half_zone$graph)$colors,
       edge.width = second_half_zone$agg_data$weight*250/
         sum(second_half_zone$agg_data$weight),
       vertex.label = V(second_half_zone$graph)$labels,
       vertex.label.font = 2,
       vertex.label.color = "black",
       vertex.label.cex = 2,
       edge.label.font = 1, 
       edge.label.cex = 1,
       vertex.label.size = 5,
       edge.arrow.size = 0.5,
       edge.curved = 0.3)
```
```{r}
## Plot Match
tkplot(match_zone$graph,
       vertex.size = match_zone$degrees*250/
         sum(match_zone$degrees),
       vertex.color = V(match_zone$graph)$colors,
       edge.width = match_zone$agg_data$weight*250/
         sum(match_zone$agg_data$weight),
       vertex.label = V(match_zone$graph)$labels,
       vertex.label.font = 2,
       vertex.label.color = "black",
       vertex.label.cex = 2,
       edge.label.font = 1, 
       edge.label.cex = 1,
       vertex.label.size = 5,
       edge.arrow.size = 0.5,
       edge.curved = 0.3)
```


### Community Detection
```{r}
## First Half, g_first_half
## Second Half, g_second_half 
## whole match, g_all 

## First Half
out_first  <- community_detection(g_first_half$graph)
```

```{r}
## Second Half
out_second <- community_detection(g_second_half$graph)
```

```{r}
## Match
out_match  <- community_detection(g_all$graph)
```

```{r}
## How many communities?
length(unique(out_match$clp_edge_betw$membership))
length(unique(out_match$clp_label_prop$membership))
length(unique(out_match$clp_walktrap_prop$membership))
length(unique(out_match$clp_infomap_prop$membership))

## Modularity
modularity(out_match$clp_edge_betw)
modularity(out_match$clp_label_prop)
modularity(out_match$clp_walktrap_prop)
modularity(out_match$clp_infomap_prop)
```

```{r}
## Dendogram Edge-Betwenness
plot_dendrogram(out_match$clp_edge_betw)
```


```{r}
## Dendogram Walktrap
plot_dendrogram(out_match$clp_walktrap_prop)
```









